services:

  # Postgres database service
  postgres-database:
    container_name: postgres-db
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev-hub

  # PGAdmin service
  pg-admin:
    container_name: pg-admin
    image: dpage/pgadmin4:8.8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_backups:/var/lib/pgadmin/storage
    depends_on:
      - postgres-database

  # Data layer service
  data-layer:
    image: dev-hub-data
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgresql://postgres:password@postgres-database:5432/dev-hub
    ports:
      - "3000:3000"
    depends_on:
      - postgres-database